import {before,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {bootDatabase,createUser,db,mockNextRuntime} from './helpers/harness';
mockNextRuntime();
const uid='d2000000-0000-4000-8000-000000000001';
let first:{sessionToken:string;deviceToken:string};
const password='LongPassword123!';
let otp='';
const send=async (_email:string,_template:string,vars:Record<string,string>)=>{otp=vars.transfer_code;return {accepted:true,messageId:'mock-id'};};
before(async()=>{await bootDatabase();first=await createUser(uid);const {hashPassword}=await import('../lib/auth/password');
  await db.query('update app_users set password_hash=$2 where id=$1',[uid,await hashPassword(password)]);
});
after(()=>db.close());
test('six-digit device transfer revokes old session, keeps trial and rejects reuse',async()=>{
  const {requestDeviceTransfer,confirmDeviceTransfer}=await import('../lib/auth/device-transfer');
  const email=`${uid}@example.test`;
  const initial=(await db.query<{device_hash:string;ends_at:string}>('select device_hash,ends_at from user_trials where user_id=$1',[uid])).rows[0];
  const issued=await requestDeviceTransfer(email,password,{send:send as never});
  assert.match(issued.maskedEmail,/^d\*\*\*@/);
  assert.match(otp,/^\d{6}$/);
  const row=(await db.query<{token_hash:string;attempts:number}>('select token_hash,attempts from device_transfers where user_id=$1',[uid])).rows[0];
  assert.notEqual(row.token_hash,otp);
  assert.equal((await db.query<{n:number}>("select count(*)::int n from email_logs where template_key='device_transfer'")).rows[0].n,0,'raw OTP never enters queue snapshots');
  await assert.rejects(confirmDeviceTransfer(email,otp==='000000'?'000001':'000000','a'.repeat(64)),/غير صحيح/);
  assert.equal((await db.query<{attempts:number}>('select attempts from device_transfers where user_id=$1',[uid])).rows[0].attempts,1);
  const second=await confirmDeviceTransfer(email,otp,'a'.repeat(64));
  assert.equal(second.deviceToken,'a'.repeat(64));
  const {findSessionProfile}=await import('../lib/auth/session-store');
  assert.equal(await findSessionProfile(first.sessionToken,first.deviceToken),null);
  assert.ok(await findSessionProfile(second.sessionToken,second.deviceToken));
  const afterTrial=(await db.query<{device_hash:string;ends_at:string}>('select device_hash,ends_at from user_trials where user_id=$1',[uid])).rows[0];
  assert.notEqual(afterTrial.device_hash,initial.device_hash);
  assert.equal(new Date(afterTrial.ends_at).getTime(),new Date(initial.ends_at).getTime());
  await assert.rejects(confirmDeviceTransfer(email,otp,'b'.repeat(64)));
  const events=(await db.query<{event_type:string}>('select event_type from device_transfer_events where user_id=$1',[uid])).rows.map(r=>r.event_type);
  assert.ok(events.includes('DEVICE_TRANSFER_OTP_SENT')&&events.includes('DEVICE_TRANSFER_SUCCESS')&&events.includes('DEVICE_TRANSFER_DENIED'));
  assert.doesNotMatch(JSON.stringify(events),new RegExp(otp));
});
test('five wrong codes lock transfer and expiry denies verification',async()=>{
  const {requestDeviceTransfer,confirmDeviceTransfer}=await import('../lib/auth/device-transfer');
  const email=`${uid}@example.test`;
  await requestDeviceTransfer(email,password,{send:send as never});
  for(let i=0;i<5;i++)await assert.rejects(confirmDeviceTransfer(email,otp==='999999'?'999998':'999999'));
  await assert.rejects(confirmDeviceTransfer(email,otp));
  assert.equal((await db.query<{attempts:number}>('select attempts from device_transfers where user_id=$1',[uid])).rows[0].attempts,5);
  await db.query("update device_transfers set created_at=now()-interval '61 seconds' where user_id=$1",[uid]);
  await requestDeviceTransfer(email,password,{send:send as never});
  await db.query("update device_transfers set expires_at=now()-interval '1 second' where user_id=$1",[uid]);
  await assert.rejects(confirmDeviceTransfer(email,otp));
});
test('resend cooldown does not replace a valid code and failed delivery invalidates its code',async()=>{
  const another='d2000000-0000-4000-8000-000000000002';
  await createUser(another);
  const {hashPassword}=await import('../lib/auth/password');
  await db.query('update app_users set password_hash=$2 where id=$1',[another,await hashPassword(password)]);
  const {requestDeviceTransfer}=await import('../lib/auth/device-transfer');
  const email=`${another}@example.test`;
  await requestDeviceTransfer(email,password,{send:send as never});
  const before=(await db.query<{token_hash:string}>('select token_hash from device_transfers where user_id=$1',[another])).rows[0].token_hash;
  const resend=await requestDeviceTransfer(email,password,{send:async()=>{throw new Error('cooldown must prevent sending');}});
  assert.ok(resend.retryAfterSeconds>0);
  assert.equal((await db.query<{token_hash:string}>('select token_hash from device_transfers where user_id=$1',[another])).rows[0].token_hash,before);
  await db.query("update device_transfers set created_at=now()-interval '61 seconds' where user_id=$1",[another]);
  await assert.rejects(requestDeviceTransfer(email,password,{send:async()=>{throw new Error('SMTP unavailable');}}),/تعذر إرسال/);
  assert.equal((await db.query<{n:number}>('select count(*)::int n from device_transfers where user_id=$1',[another])).rows[0].n,0);
  assert.equal((await db.query<{n:number}>("select count(*)::int n from device_transfer_events where user_id=$1 and event_type='DEVICE_TRANSFER_OTP_FAILED'",[another])).rows[0].n,1);
});
