import {before,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {vector} from '@electric-sql/pglite-pgvector';
import {migrate} from '../scripts/migrate.mjs';
import {identityDb,workerDb} from '../lib/tutor/db';
import {registerDocument,processKnowledgeDocument,enqueueDocument} from '../lib/tutor/ingestion';
import {retrieveKnowledge} from '../lib/tutor/retrieval';
import {recordTutorTurn,loadTutorContext,matchAssignedSubject} from '../lib/tutor/memory';
import {handleTutorChat} from '../lib/tutor/chat';
import {DatabaseClient} from '../lib/db/server';
import {confirmedClinicalSupport,requiresClinicalEvidence,streamTutorAnswer,type TutorAnswer} from '../lib/tutor/answer';
import {structureChunks} from '../lib/tutor/chunking';
const db=new PGlite({extensions:{vector}}),uid='30000000-0000-4000-8000-000000000001',other='30000000-0000-4000-8000-000000000002',admin='30000000-0000-4000-8000-000000000003';
let subject:string,year:string,privateId:string,cid:string,docId:string,embeddingCalls=0,chatCalls=0;
let tail=Promise.resolve();
async function acquire(){let release!:()=>void;const previous=tail;tail=new Promise<void>(r=>{release=r;});await previous;return release;}
async function direct(sql:string,values?:unknown[]){const result=await db.query<Record<string,unknown>>(sql,values);for(const row of result.rows){for(const [key,value] of Object.entries(row))if(value instanceof Uint8Array)row[key]=Buffer.from(value);}return result;}
const pool={query:async(sql:string,values?:unknown[])=>{const unlock=await acquire();try{return await direct(sql,values);}finally{unlock();}},connect:async()=>{let unlock:(()=>void)|undefined;return {query:async(sql:string,values?:unknown[])=>{if(sql==='BEGIN'){unlock=await acquire();return direct(sql,values);}if(unlock){try{return await direct(sql,values);}finally{if(sql==='COMMIT'||sql==='ROLLBACK'){unlock();unlock=undefined;}}}const done=await acquire();try{return await direct(sql,values);}finally{done();}},release(){unlock?.();unlock=undefined;}};}};
const baseAnswer: TutorAnswer={answer:'A compound microscope uses an objective lens and an eyepiece.\n\nObjective lens — العدسة الشيئية.',answer_origin:'curriculum',source_ids:['S1'],clinical_support:[],topic:'Microscope lenses',clarification_needed:false,out_of_scope:false,quiz:null,quiz_result:'not_answered',preference:null};
before(async()=>{process.env.DATABASE_URL='postgresql://test-only';process.env.OPENAI_API_KEY='contract-test-key';delete process.env.AI_ARCHITECTURE;Object.assign(globalThis,{nursingPool:pool});await migrate({query:async(sql:string,values?:unknown[])=>{if(!values&&(sql.includes(';')||sql.includes('--'))){await db.exec(sql);return {rows:[]};}return db.query(sql,values);}});year=(await db.query<{id:string}>("select id from academic_years where code='first_year'")).rows[0].id;
 subject=(await db.query<{id:string}>("insert into subjects(name_ar,name_en) values('الأحياء','Biology (BIOL 101)') returning id")).rows[0].id;await db.query('insert into subject_academic_years(subject_id,academic_year_id) values($1,$2)',[subject,year]);
 for(const [id,name,role] of [[uid,'Ahmad','student'],[other,'Other','student'],[admin,'Admin','admin']]){await db.query("insert into app_users(id,email,password_hash) values($1,$2,'test')",[id,`${id}@example.test`]);await db.query('insert into profiles(user_id,email,full_name,role,academic_year_id) values($1,$2,$3,$4,$5)',[id,`${id}@example.test`,name,role,year]);}
 cid=(await db.query<{id:string}>("insert into conversations(user_id,subject_id,title) values($1,$2,'Microscope study') returning id",[uid,subject])).rows[0].id;
 await db.query("update settings set value='0'::jsonb where key='rate_limit_seconds'");
 await db.query("update settings set value='200'::jsonb where key='free_daily_limit'");
 await db.exec('create role tutor_runtime nosuperuser nobypassrls; grant usage on schema public to tutor_runtime; grant select,insert,update,delete on all tables in schema public to tutor_runtime; grant usage,select on all sequences in schema public to tutor_runtime');
});after(()=>db.close());
test('structure chunks retain table headers, definitions and all source content',()=>{const table='Drug | Action | Nursing consideration\n'+Array.from({length:180},(_,i)=>`Drug${i} | Action${i} | Consideration${i}`).join('\n');const chunks=structureChunks(table,100,150);assert.ok(chunks.length>2);assert.ok(chunks.every(c=>c.content.includes('Drug | Action | Nursing consideration')));assert.ok(chunks.some(c=>c.content.includes('Drug179')));});
test('non-superuser RLS denies unscoped and foreign conversations, messages, memory and private chunks',async()=>{
 privateId=(await workerDb.query<{id:string}>(`insert into knowledge_documents(owner_id,title,original_file_name,storage_path,subject_id,source_type,is_active) values($1,'Private','private.txt','private-test',$2,'student_private_file',true) returning id`,[uid,subject])).rows[0].id;
 await workerDb.query("insert into knowledge_chunks(document_id,subject_id,source_type,source_priority,content,content_hash,embedding,chunk_index,token_count) values($1,$2,'student_private_file',100,'PRIVATE OWNER ONLY','private-hash',$3::vector,0,4)",[privateId,subject,`[${Array(1536).fill(0.1)}]`]);
 await workerDb.query(`insert into student_memory(user_id,memory_type,memory_key,memory_value_json) values($1,'preference','language','"English"'::jsonb)`,[uid]);
 await db.query('set role tutor_runtime');
 try{assert.equal((await db.query('select id from conversations')).rows.length,0);assert.equal((await identityDb(other).query('select id from conversations where id=$1',[cid])).rows.length,0);assert.equal((await identityDb(other).query('select id from knowledge_chunks where document_id=$1',[privateId])).rows.length,0);assert.equal((await identityDb(other).query('select id from student_memory where user_id=$1',[uid])).rows.length,0);await assert.rejects(identityDb(other).query("insert into conversation_summaries(conversation_id,user_id) values($1,$2)",[cid,other]),/row-level security/);assert.equal((await identityDb(uid).query('select id from knowledge_chunks where document_id=$1',[privateId])).rows.length,1);}
 finally{await db.query('reset role');}
});
test('canonical index embeds once, publishes atomically and hybrid retrieval isolates private files',async t=>{
 t.mock.method(globalThis,'fetch',async(url:RequestInfo|URL,init?:RequestInit)=>{assert.ok(String(url).includes('/embeddings'));embeddingCalls++;const body=JSON.parse(String(init?.body)),texts=Array.isArray(body.input)?body.input:[body.input];return Response.json({model:'text-embedding-3-small',data:texts.map((_:string,index:number)=>({index,embedding:Array.from({length:1536},(_,i)=>i===0?1:0)})),usage:{total_tokens:20}});});
 const text='Compound microscope\n\nA compound microscope uses an objective lens and an eyepiece. The objective lens forms the initial magnified image. The eyepiece magnifies this image further.';
 await db.query("insert into stored_files(path,bucket,owner_id,mime_type,content) values('canonical-fixture','knowledge-documents',$1,'text/plain',$2)",[admin,Buffer.from(text)]);
 docId=(await db.query<{id:string}>("insert into documents(title,file_name,file_url,subject_id,created_by,source_type) values('Microscope lecture','microscope.txt','canonical-fixture',$1,$2,'university_lecture') returning id",[subject,admin])).rows[0].id;
 const id=await registerDocument(docId);await processKnowledgeDocument(id);const calls=embeddingCalls;await processKnowledgeDocument(id);assert.equal(embeddingCalls,calls);const ready=(await workerDb.query('select * from knowledge_documents where id=$1',[id])).rows[0];assert.equal(ready.status,'ready');assert.equal(ready.chunk_count,ready.embedding_count);assert.ok(Number(ready.chunk_count)>0);assert.equal(ready.is_active,false);
 await workerDb.query("update knowledge_documents set is_active=true,publication_status='published' where id=$1",[id]);
 await db.query('set role tutor_runtime');try{const found=await retrieveKnowledge('اشرح وظيفة العدسة في المجهر',{userId:other,subjectId:subject});assert.ok(found.sources.some(s=>s.title==='Microscope lecture'));assert.ok(found.sources.every(s=>s.ownerId!==uid));assert.ok(found.sources[0].scores.lexical>0);await assert.rejects(workerDb.query("update knowledge_documents set chunk_count=0 where id=$1",[id]),/check constraint/);}finally{await db.query('reset role');}
});
test('profile course matching and learning memory use assessed answers only and survive a new conversation',async()=>{
 const context=await loadTutorContext(uid,cid,'I want to study Biology today.');assert.equal(context.profile.full_name,'Ahmad');assert.equal(matchAssignedSubject('I want to study Biology today.',context.subjects),subject);assert.equal(matchAssignedSubject('بدي أدرس أحياء',context.subjects),subject);
 const message=(await db.query<{id:string}>("insert into messages(conversation_id,role,content) values($1,'assistant','Quiz') returning id",[cid])).rows[0].id,pending={question:'Which lens forms the initial image?',options:['Objective','Eyepiece'],correct_option:'A',explanation:'The objective forms the first image.',topic:'Microscope lenses'};
 await recordTutorTurn({userId:uid,conversationId:cid,messageId:message,subjectId:subject,documentId:null,attachmentId:null,question:'B',answer:{...baseAnswer,quiz_result:'incorrect'},pendingQuiz:pending});
 await recordTutorTurn({userId:uid,conversationId:cid,messageId:message,subjectId:subject,documentId:null,attachmentId:null,question:'B',answer:{...baseAnswer,quiz_result:'incorrect'},pendingQuiz:pending});
 assert.equal((await identityDb(uid).query('select wrong_answers from student_topic_progress where user_id=$1',[uid])).rows[0].wrong_answers,1);
 const fresh=(await db.query<{id:string}>("insert into conversations(user_id,title) values($1,'Next day') returning id",[uid])).rows[0].id;
 const resumed=await loadTutorContext(uid,fresh,'Continue from where we stopped.');assert.equal(resumed.summary?.conversation_id,cid);assert.match(resumed.text,/Microscope lenses/);assert.match(resumed.text,/incorrect":1/);
});
test('chat HTTP streaming contract saves answer, verified metadata, usage and memory without leaking JSON keys',async t=>{
 t.mock.method(globalThis,'fetch',async(url:RequestInfo|URL,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));if(String(url).includes('/embeddings'))return Response.json({data:[{index:0,embedding:Array.from({length:1536},(_,i)=>i===0?1:0)}],usage:{total_tokens:8}});chatCalls++;assert.equal(body.model,'gpt-6-luna');assert.equal(body.store,false);assert.equal(body.stream,true);assert.match(String(body.instructions),/Academic English is the primary teaching language/);assert.match(String(body.instructions),/There is no "NO SOURCE = NO ANSWER" rule/);const answer=JSON.stringify(baseAnswer);let stream='';for(let i=0;i<answer.length;i+=9)stream+=`event: response.output_text.delta\ndata: ${JSON.stringify({type:'response.output_text.delta',delta:answer.slice(i,i+9)})}\n\n`;stream+=`event: response.completed\ndata: ${JSON.stringify({type:'response.completed',response:{status:'completed',model:'gpt-6-luna',output:[],output_text:answer,usage:{input_tokens:1200,output_tokens:80,input_tokens_details:{cached_tokens:800}}}})}\n\ndata: [DONE]\n\n`;return new Response(stream,{headers:{'Content-Type':'text/event-stream'}});});
 await db.query('set role tutor_runtime');try{const request=new Request('https://nursing.example.test/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversationId:cid,content:'Explain the microscope lenses.',subjectId:subject})});const response=await handleTutorChat(request,new DatabaseClient({user_id:uid,role:'student',status:'active'}),()=>{});assert.equal(response.status,200);const text=await response.text();assert.match(text,/objective lens/);assert.match(text,/Microscope lecture/);assert.doesNotMatch(text,/quiz_result|correct_option|clinical_support/);const saved=(await identityDb(uid).query("select * from messages where conversation_id=$1 and role='assistant' order by created_at desc limit 1",[cid])).rows[0];assert.equal(saved.answer_origin,'curriculum');assert.ok(Array.isArray(saved.source_ids));const usage=(await db.query<{cached_input_tokens:number;estimated_cost:number}>("select * from usage_logs where feature='chat' and success=true order by created_at desc limit 1")).rows[0];assert.equal(usage.cached_input_tokens,800);assert.ok(Number(usage.estimated_cost)>0);assert.equal(chatCalls,1);assert.equal((await identityDb(other).query('select id from messages where conversation_id=$1',[cid])).rows.length,0);}finally{await db.query('reset role');}
});
test('clinical numeric gate requires real source quotes and rejects invented values',()=>{const answer={...baseAnswer,answer:'The dose is 50 mg.',clinical_support:[{source_id:'S1',quote:'The dose in the lecture is 5 mg.'}]};const sources=[{content:'The dose in the lecture is 5 mg.',sourceType:'required_textbook',similarity:1}];assert.equal(confirmedClinicalSupport(answer,sources),false);assert.equal(confirmedClinicalSupport({...answer,answer:'The dose is 5 mg.'},sources),true);assert.equal(requiresClinicalEvidence('What dose should be used?'),true);});
import {analyzeConversationAttachment,loadConversationAttachments,resolveConversationReference,attachmentEvidence,persistResolvedAttachmentState,visionContextSchema,type ConversationAttachment} from '../lib/ai/conversation-context';
import {getAIProvider} from '../lib/ai';
import {attachProcessedLecture} from '../lib/tutor/file-attachment';
import {consumeChatResponse} from '../lib/chat/stream';
import {strictResponseSchema} from '../lib/ai/providers/openai';
import {generateStudyContent} from '../lib/lectures/study-content';
function responseStream(answer:TutorAnswer){const content=JSON.stringify(answer);let text='';for(let i=0;i<content.length;i+=7)text+=`event: response.output_text.delta\ndata: ${JSON.stringify({type:'response.output_text.delta',delta:content.slice(i,i+7)})}\n\n`;text+=`event: response.completed\ndata: ${JSON.stringify({type:'response.completed',response:{status:'completed',model:'gpt-6-luna',output:[],output_text:content,usage:{input_tokens:900,output_tokens:90,input_tokens_details:{cached_tokens:600}}}})}\n\ndata: [DONE]\n\n`;return new Response(text,{headers:{'Content-Type':'text/event-stream'}});}
test('image analysis is cached per student, follows ordered sections and persists section position under RLS',async t=>{
 let visionCalls=0;const vision=visionContextSchema.parse({document_type:'lecture_slide',subject_guess:'Biology',topic:'Compound microscope',extracted_text:'Objective lens forms the image. Eyepiece magnifies it.',sections:[{index:1,title:'Objective lens',text:'The objective lens forms the initial image.'},{index:2,title:'Eyepiece',text:'The eyepiece magnifies the image.'}],medical_terms:['Objective lens','Eyepiece'],tables:[],unclear_regions:[]});
 t.mock.method(globalThis,'fetch',async()=>{visionCalls++;return Response.json({status:'completed',model:'gpt-6-luna',output:[],output_text:JSON.stringify(vision),usage:{input_tokens:120,output_tokens:90}});});
 const imageCid=(await db.query<{id:string}>("insert into conversations(user_id,title,subject_id) values($1,'Image session',$2) returning id",[uid,subject])).rows[0].id;
 await db.query('set role tutor_runtime');try{const provider=getAIProvider(),first=await analyzeConversationAttachment({conversationId:imageCid,messageId:null as unknown as string,userId:uid,filePath:'fixture-image-1',imageDataUri:'data:image/png;base64,ZmFrZQ==',subjectId:subject,lectureId:null,provider});assert.equal(first.cacheHit,false);
 const again=await analyzeConversationAttachment({conversationId:imageCid,messageId:null as unknown as string,userId:uid,filePath:'fixture-image-1',imageDataUri:'data:image/png;base64,ZmFrZQ==',subjectId:subject,lectureId:null,provider});assert.equal(again.cacheHit,true);assert.equal(visionCalls,1);
 const attachments=await loadConversationAttachments(imageCid,uid),resolved=resolveConversationReference({question:'Explain the first part in Arabic too.',...attachments});assert.equal(resolved.selectedSectionIndex,1);await persistResolvedAttachmentState({conversationId:imageCid,userId:uid,attachmentId:first.attachment.id,sectionIndex:1});const loaded=await loadConversationAttachments(imageCid,uid);assert.equal(loaded.activeSectionIndex,1);const next=resolveConversationReference({question:'كمل',...loaded});assert.equal(next.selectedSectionIndex,2);
 const newCid=(await identityDb(uid).query<{id:string}>("insert into conversations(user_id,title) values($1,'New image session') returning id",[uid])).rows[0].id;const copied=await analyzeConversationAttachment({conversationId:newCid,messageId:null as unknown as string,userId:uid,filePath:'fixture-image-duplicate',imageDataUri:'data:image/png;base64,ZmFrZQ==',subjectId:subject,lectureId:null,provider});assert.equal(copied.cacheHit,true);assert.equal(visionCalls,1);assert.equal((await identityDb(other).query('select id from conversation_attachments where id=$1',[first.attachment.id])).rows.length,0);
 }finally{await db.query('reset role');}
});
test('private page-five file context, quiz key, incorrect answer and study-content cache remain scoped',async t=>{
 const fileCid=(await db.query<{id:string}>("insert into conversations(user_id,title,subject_id) values($1,'File session',$2) returning id",[uid,subject])).rows[0].id;
 const lecture=(await db.query<{id:string}>(`insert into lectures(user_id,subject_id,title,file_name,original_file_name,storage_path,mime_type,file_size_bytes,file_hash,status) values($1,$2,'Private PDF','lesson.pdf','lesson.pdf','private-pdf','application/pdf',100,'private-pdf-hash','ready') returning id`,[uid,subject])).rows[0].id;
 const pages=Array.from({length:6},(_,i)=>({pageNumber:i+1,text:`Section on page ${i+1}: ${i===4?'The objective lens forms the initial microscope image.':'Different study context.'}`}));
 const kd=await registerDocument(lecture,true);await workerDb.query(`update knowledge_documents set extracted_pages_json=$2::jsonb,page_count=6,extracted_text_length=500,chunk_count=1,embedding_count=1,index_version=3,status='ready' where id=$1`,[kd,JSON.stringify(pages)]);await workerDb.query(`insert into knowledge_chunks(document_id,subject_id,source_type,source_priority,page_number,chunk_index,content,content_hash,embedding,token_count) values($1,$2,'student_private_file',100,5,0,'The objective lens forms the initial microscope image.','private-page5',$3::vector,12)`,[kd,subject,`[${Array.from({length:1536},(_,i)=>i===0?1:0)}]`]);
 let mainCalls=0,studyCalls=0;
 t.mock.method(globalThis,'fetch',async(url:RequestInfo|URL,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));if(String(url).includes('/embeddings'))return Response.json({data:[{index:0,embedding:Array.from({length:1536},(_,i)=>i===0?1:0)}],usage:{total_tokens:5}});
 if(!body.stream){studyCalls++;assert.match(String(body.instructions),/Write each front in English/);assert.match(String(body.instructions),/Arabic meaning/);return Response.json({status:'completed',model:'gpt-6-luna',output:[],output_text:JSON.stringify({cards:[{front:'Which lens forms the first image?',back:'Objective lens'}]}),usage:{input_tokens:100,output_tokens:30}});}
 mainCalls++;let answer:TutorAnswer={...baseAnswer,answer_origin:'student_file',answer:'Page five explains the objective lens.',source_ids:['S1']};if(mainCalls===2)answer={...answer,answer:'Which lens forms the initial image?\n\nA) Objective lens\nB) Eyepiece',quiz:{question:'Which lens forms the initial image?',options:['Objective lens','Eyepiece'],correct_option:'A',explanation:'The objective lens forms it.',topic:'Microscope lenses'}};if(mainCalls===3){const data=JSON.parse(body.input[0].content);assert.equal(data.deterministicQuizResult,false);answer={...answer,answer:'B is incorrect. The objective lens forms the initial image; the eyepiece magnifies it.',quiz_result:'correct'};}return responseStream(answer);});
 await db.query('set role tutor_runtime');try{const attachment=await attachProcessedLecture(uid,fileCid,lecture);let savedId='';async function send(content:string){const response=await handleTutorChat(new Request('https://nursing.example.test/api/chat',{method:'POST',headers:{'Content-Type':'application/json',Accept:'text/event-stream'},body:JSON.stringify({conversationId:fileCid,content,attachmentId:attachment,lectureId:lecture})}),new DatabaseClient({user_id:uid,role:'student',status:'active'}),()=>{});let text='';await consumeChatResponse(response,{onConversationId(){},onChunk(delta){text+=delta;},onMessageIds(id){savedId=id;},onComplete(){}});return text;}
 const taught=await send('Teach me page 5.');assert.match(taught,/Page five/);assert.match(taught,/Page 5/);assert.ok(/^[a-f0-9-]{36}$/.test(savedId));const question=await send('Make me one question about it.');assert.match(question,/A\) Objective/);assert.doesNotMatch(question,/correct_option|answer_key/);await send('B');const event=(await identityDb(uid).query("select event_type from learning_events where message_id=$1",[savedId])).rows[0];assert.equal(event.event_type,'quiz_incorrect');await assert.rejects(attachProcessedLecture(other,fileCid,lecture));const first=await generateStudyContent(lecture,uid,'flashcards','Private PDF');const again=await generateStudyContent(lecture,uid,'flashcards','Private PDF');assert.deepEqual(first,again);assert.equal(studyCalls,1);assert.equal((await identityDb(other).query('select path from stored_files where owner_id=$1',[uid])).rows.length,0);assert.equal((await identityDb(other).query('select id from lectures where id=$1',[lecture])).rows.length,0);
 }finally{await db.query('reset role');}
});
test('strict Responses schemas convert every optional nested field into a required nullable field',()=>{const result=strictResponseSchema({type:'object',properties:{key:{type:'string'},value:{type:'object',properties:{option:{type:'string'}}}},required:['key']});assert.deepEqual(result.required,['key','value']);assert.equal(result.additionalProperties,false);const properties=result.properties as Record<string,Record<string,unknown>>;const value=(properties.value.anyOf as Array<Record<string,unknown>>)[0];assert.deepEqual(value.required,['option']);assert.equal(value.additionalProperties,false);});
test('large file follow-ups stay bounded and missing cached pages never fall back to the whole book',()=>{
 const attachment={id:'bounded-file',ordinal:1,file_type:'file',vision_extracted_text:'WHOLE_BOOK_SENTINEL'.repeat(10000),vision_structured_json:{topic:'Biology',subject_guess:'Biology',sections:Array.from({length:30},(_,i)=>({index:i+1,title:`Page ${i+1}`,text:`Page ${i+1} `+'large page text '.repeat(1000)})),medical_terms:[]}} as unknown as ConversationAttachment;
 const common={attachments:[attachment],activeAttachmentId:attachment.id,activeSectionIndex:1};
 const ordinary=resolveConversationReference({question:'Explain this file.',...common});assert.ok(ordinary.resolvedQuestion.length<4000);assert.doesNotMatch(ordinary.resolvedQuestion,/Page 30/);assert.equal(attachmentEvidence(ordinary).length,3);
 const missing=resolveConversationReference({question:'Teach me page 45.',...common});assert.equal(missing.selectedSectionIndex,45);assert.equal(attachmentEvidence(missing).length,0);assert.doesNotMatch(missing.resolvedQuestion,/WHOLE_BOOK_SENTINEL|large page text/);
 assert.equal(requiresClinicalEvidence('What is the normal potassium level?'),true);
});
test('explicit reindex rebuilds a ready source without repeating paid embeddings',async t=>{
 t.mock.method(globalThis,'fetch',async()=>{throw new Error('Cached reindex must not call OpenAI');});
 const document=(await workerDb.query<{id:string}>('select id from knowledge_documents where legacy_document_id=$1',[docId])).rows[0];assert.ok(document);
 await enqueueDocument(document.id,true);assert.equal((await workerDb.query('select status from knowledge_documents where id=$1',[document.id])).rows[0].status,'uploaded');
 await processKnowledgeDocument(document.id);const ready=(await workerDb.query('select status,index_version from knowledge_documents where id=$1',[document.id])).rows[0];assert.equal(ready.status,'ready');assert.equal(ready.index_version,3);
});
test('ordinary general knowledge streams while unsupported clinical follow-ups are withheld',async t=>{
 let mode='general';t.mock.method(globalThis,'fetch',async()=>responseStream({...baseAnswer,source_ids:[],answer_origin:'general_nursing_knowledge',answer:mode==='general'?'Empathy means understanding a patient’s perspective.':'Use a dose of 20 mg.'}));
 let displayed='';const general=await streamTutorAnswer({question:'Explain empathy in nursing.',history:[],context:'Nursing student',sources:[],pendingQuiz:null,onDelta:delta=>{displayed+=delta;}});assert.match(displayed,/Empathy/);assert.equal(general.answer.answer_origin,'general_nursing_knowledge');assert.equal(general.answer.clarification_needed,false);
 mode='clinical';displayed='';const guarded=await streamTutorAnswer({question:'What about a child?',originalQuestion:'What about a child?',history:[{role:'user',content:'Which drug dose should be used?'}],context:'Nursing student',sources:[],pendingQuiz:null,onDelta:delta=>{displayed+=delta;}});assert.doesNotMatch(displayed,/20 mg/);assert.equal(guarded.answer.clarification_needed,true);assert.match(displayed,/confirm|نتحقق/);
});
