import type { AIProvider, EmbeddingResult, GenerateResult, GenerateTextParams, StreamChunk } from "@/lib/ai/provider";
import { buildKnowledgeContext, NURSING_SYSTEM_PROMPT } from "@/lib/ai/system-prompt";
const baseUrl = () => (process.env.OLLAMA_BASE_URL?.trim() || "http://127.0.0.1:11434").replace(/\/$/, "");
const chatModel = () => process.env.OLLAMA_CHAT_MODEL?.trim() || "qwen2.5:3b";
const embeddingModel = () => process.env.OLLAMA_EMBEDDING_MODEL?.trim() || "nomic-embed-text";
function prompt(p: GenerateTextParams) { return NURSING_SYSTEM_PROMPT + (p.personalizationContext ? `\n\nStudent personalization context (not a source):\n${p.personalizationContext}` : "") + (p.knowledge?.length ? buildKnowledgeContext(p.knowledge) : ""); }
function bodyMessages(p: GenerateTextParams) { return [{ role: "system", content: prompt(p) }, ...p.messages.map((m) => ({ role: m.role, content: m.content }))]; }
async function post(path: string, body: unknown, signal?: AbortSignal) { let r: Response; try { r = await fetch(`${baseUrl()}${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body), signal }); } catch { throw new Error("تعذر الاتصال بـ Ollama. تأكد أن الخدمة تعمل."); } if (!r.ok) throw new Error(`Ollama request failed (${r.status})`); return r; }
export class OllamaProvider implements AIProvider {
  async generateText(p: GenerateTextParams): Promise<GenerateResult> { const model = chatModel(); const r = await post("/api/chat", { model, messages: bodyMessages(p), stream: false, think: false, options: p.maxOutputTokens ? { num_predict: p.maxOutputTokens } : undefined }, p.signal); const d = await r.json() as { message?: { content?: string }; prompt_eval_count?: number; eval_count?: number }; return { content: d.message?.content ?? "", inputTokens: d.prompt_eval_count ?? 0, outputTokens: d.eval_count ?? 0, model }; }
  async *generateStream(p: GenerateTextParams): AsyncGenerator<StreamChunk, GenerateResult, unknown> { const model = chatModel(); const r = await post("/api/chat", { model, messages: bodyMessages(p), stream: true, think: false, options: p.maxOutputTokens ? { num_predict: p.maxOutputTokens } : undefined }, p.signal); if (!r.body) throw new Error("Ollama stream غير صالح."); const reader = r.body.getReader(); const decoder = new TextDecoder(); let buf="", content=""; let inputTokens=0, outputTokens=0; const parse=(line:string)=>{ if(!line.trim()) return; const d=JSON.parse(line) as {message?:{content?:string};prompt_eval_count?:number;eval_count?:number}; if(d.prompt_eval_count) inputTokens=d.prompt_eval_count; if(d.eval_count) outputTokens=d.eval_count; const delta=d.message?.content ?? ""; if(delta){content+=delta; return delta;} }; while(true){const {value,done}=await reader.read(); if(done) break; buf+=decoder.decode(value,{stream:true}); const lines=buf.split("\n"); buf=lines.pop()??""; for(const line of lines){const delta=parse(line); if(delta) yield {delta};}} if(buf.trim()){const delta=parse(buf); if(delta) yield {delta};} return {content,inputTokens,outputTokens,model}; }
  async generateVisionResponse(): Promise<GenerateResult> { throw new Error("Vision غير مدعوم حاليًا في مزود Ollama المحلي بهذا النموذج."); }
  async createEmbedding(text:string){const [r]=await this.createEmbeddings([text]); return r;}
  async createEmbeddings(texts:string[]):Promise<EmbeddingResult[]>{if(!texts.length)return[]; const model=embeddingModel(); const r=await post("/api/embed",{model,input:texts}); const d=await r.json() as {embeddings?:number[][]}; if(!d.embeddings?.length) throw new Error("Ollama لم يُرجع embeddings."); return d.embeddings.map(embedding=>({embedding,tokens:0,model}));}
  calculateCost(){return 0;}
}
