import { requireAdminProfile } from "@/lib/auth";
import { getAdminSubscriptionData } from "@/lib/subscriptions/queries";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Mail } from "lucide-react";
import { retryEmailAction,saveTemplateAction,testSmtpAction,updateSmtpAction } from "../actions";

export default async function EmailSettingsPage(){const admin=await requireAdminProfile(),data=await getAdminSubscriptionData(admin.user_id),smtp=data.emailSettings;
return <div className="page-container mx-auto max-w-6xl space-y-8"><PageHeader icon={Mail} eyebrow="الاشتراكات" title="البريد وSMTP" description="كلمة المرور مشفرة ولا تظهر مجددًا. الرسائل التشغيلية تحفظ في Queue قابلة لإعادة المحاولة."/>
<Card><CardHeader><CardTitle>إعدادات SMTP</CardTitle><CardDescription>{smtp?.has_password?"كلمة المرور محفوظة بشكل مشفر. اترك الحقل فارغًا للإبقاء عليها.":"أدخل بيانات مزود البريد."}</CardDescription></CardHeader><CardContent><form action={updateSmtpAction} className="grid gap-3 sm:grid-cols-2"><Field name="host" label="SMTP Host" value={smtp?.host??""}/><Field name="port" label="Port" type="number" value={smtp?.port??587}/><Field name="username" label="Username" value={smtp?.username??""} required={false}/><Field name="password" label={smtp?.has_password?"Password (•••••• — اتركه فارغًا)":"Password"} type="password" required={false}/><div><Label>Encryption</Label><select name="encryption" defaultValue={smtp?.encryption??"starttls"} className="h-11 w-full rounded-xl border bg-card px-3"><option value="none">None</option><option value="starttls">STARTTLS</option><option value="tls">TLS</option></select></div><Field name="fromName" label="From Name" value={smtp?.from_name??"Nursing AI"}/><Field name="fromEmail" label="From Email" type="email" value={smtp?.from_email??""}/><Button className="self-end">حفظ SMTP</Button></form><form action={testSmtpAction} className="mt-5 flex flex-wrap gap-2 border-t pt-5"><Input className="max-w-sm" name="email" type="email" placeholder="بريد الاختبار" required/><Button variant="outline">إرسال رسالة اختبار</Button></form></CardContent></Card>
<section><h2 className="mb-3 text-xl font-extrabold">القوالب والمتغيرات</h2><p className="mb-4 text-sm text-muted-foreground" dir="ltr">{'{{student_name}} {{plan_name}} {{amount}} {{currency}} {{payment_reference}} {{expiry_date}} {{days_remaining}} {{rejection_reason}}'}</p><div className="grid gap-4 lg:grid-cols-2">{data.templates.map(t=><Card key={t.template_key}><CardHeader><CardTitle className="text-base">{t.name}</CardTitle><CardDescription>{t.template_key}</CardDescription></CardHeader><CardContent><form action={saveTemplateAction} className="space-y-3"><input type="hidden" name="key" value={t.template_key}/><Field name="subject" label="العنوان" value={t.subject}/><div><Label>HTML</Label><Textarea dir="ltr" className="min-h-36 font-mono text-xs" name="html" defaultValue={t.html_body}/></div><div><Label>Text</Label><Textarea name="text" defaultValue={t.text_body}/></div><label><input name="active" type="checkbox" defaultChecked={t.active}/> مفعّل</label><Button>حفظ القالب</Button></form></CardContent></Card>)}</div></section>
<section><h2 className="mb-3 text-xl font-extrabold">سجل الإرسال</h2><div className="space-y-2">{data.logs.map(log=><Card key={log.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 py-4"><div><b dir="ltr">{log.recipient}</b><p className="text-xs text-muted-foreground">{log.template_key??"رسالة"} · {new Date(log.created_at).toLocaleString("ar-EG")}</p>{log.last_error&&<p className="max-w-xl text-xs text-destructive">{log.last_error}</p>}</div><div className="flex items-center gap-2"><Badge variant={log.status==="sent"?"secondary":log.status==="failed"?"destructive":"outline"}>{log.status}</Badge>{log.status==="failed"&&<form action={retryEmailAction}><input type="hidden" name="id" value={log.id}/><Button size="sm" variant="outline">إعادة المحاولة</Button></form>}</div></CardContent></Card>)}</div></section>
</div>}
function Field({name,label,value="",type="text",required=true}:{name:string;label:string;value?:string|number;type?:string;required?:boolean}){return <div className="space-y-1"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} defaultValue={value} required={required}/></div>}
