import { requireAdminProfile } from "@/lib/auth";
import { identityDb } from "@/lib/tutor/db";
import { replySupportTicket } from "@/lib/support";
import { revalidatePath } from "next/cache";
import { getSupportWhatsapp } from "@/lib/support-contact";
async function reply(form:FormData){"use server";const admin=await requireAdminProfile();await replySupportTicket(admin.user_id,String(form.get("id")),String(form.get("reply")));revalidatePath("/admin/support");}
async function saveWhatsapp(form:FormData){"use server";const admin=await requireAdminProfile();const number=String(form.get('number')??'').trim();if(!/^\+?[0-9]{8,15}$/.test(number))throw new Error('رقم واتساب غير صالح');
  await identityDb(admin.user_id).query("insert into settings(key,value) values('support_whatsapp_number',$1::jsonb) on conflict(key) do update set value=excluded.value,updated_at=now()",[JSON.stringify(number)]);
  await identityDb(admin.user_id).query("insert into admin_audit_logs(event_type,admin_id,metadata) values('SUPPORT_CONTACT_UPDATED',$1,$2::jsonb)",[admin.user_id,JSON.stringify({number})]);revalidatePath('/admin/support');revalidatePath('/support');}
export default async function Page(){const admin=await requireAdminProfile();const number=await getSupportWhatsapp();const tickets=(await identityDb(admin.user_id).query<{id:string;email:string;subject:string;message:string;reply:string|null;status:string}>("select id,email,subject,message,reply,status from support_tickets order by case when status='open' then 0 else 1 end,created_at desc limit 100")).rows;
 return <main className="space-y-5"><h1 className="text-2xl font-bold">طلبات المساعدة</h1><form action={saveWhatsapp} className="rounded-xl border p-5"><label className="block">رقم واتساب الدعم الرسمي<input name="number" defaultValue={number} dir="ltr" required className="mt-2 block min-h-12 w-full rounded-xl border p-3"/></label><button className="mt-3 min-h-12 rounded-xl bg-primary px-5 text-primary-foreground">حفظ رقم الدعم</button></form>{tickets.length===0&&<p>لا توجد طلبات.</p>}{tickets.map(ticket=><section key={ticket.id} className="space-y-3 rounded-xl border p-5"><h2 className="font-bold">{ticket.subject}</h2><p dir="ltr">{ticket.email}</p><p className="whitespace-pre-wrap">{ticket.message}</p><form action={reply} className="space-y-3"><input type="hidden" name="id" value={ticket.id}/><label className="block">رد الإدارة<textarea name="reply" defaultValue={ticket.reply??""} required minLength={3} maxLength={4000} className="block w-full rounded-xl border p-3"/></label><button className="min-h-12 rounded-xl bg-primary px-5 text-primary-foreground">حفظ الرد للطالب</button></form></section>)}</main>;}
