import { requireProfile } from "@/lib/auth";
import { getSubscriptionPageData } from "@/lib/subscriptions/queries";
import { PaymentRequestForm } from "@/components/subscriptions/payment-request-form";
import { Badge } from "@/components/ui/badge";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { Progress } from "@/components/ui/progress";
import { CreditCard,Check } from "lucide-react";

const labels:Record<string,string>={ai_questions_daily:"أسئلة AI اليوم",images_limit:"الصور",files_limit:"الملفات",study_pack_limit:"إنشاء حزم الدراسة",quiz_limit:"إنشاء الاختبارات"};
const statuses:Record<string,string>={pending:"قيد المراجعة",approved:"مقبول",rejected:"مرفوض",cancelled:"ملغي"};

export default async function SubscriptionPage(){const profile=await requireProfile();const data=await getSubscriptionPageData(profile.user_id);
  return <div className="page-container mx-auto max-w-6xl space-y-8"><PageHeader icon={CreditCard} eyebrow="الحساب والفوترة" title="اشتراكي" description="تابع الباقة والاستخدام، أو أرسل إثبات دفع للتجديد دون فقد الأيام المتبقية." />
    <Card className={data.access.active?"border-primary/25":"border-destructive/30"}><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>{data.access.planName}</CardTitle><CardDescription>{data.access.active?`${data.access.daysRemaining} يوم متبقٍ`:"انتهى اشتراكك — بياناتك السابقة محفوظة ويمكنك فتحها"}</CardDescription></div><Badge variant={data.access.active?"secondary":"destructive"}>{data.access.kind==="trial"?"تجربة مجانية":data.access.kind==="paid"?"فعال":data.access.kind==="grace"?"مهلة دفع":"منتهي"}</Badge></div></CardHeader>
      <CardContent className="grid gap-3 sm:grid-cols-2">{data.usage.map(item=><div key={item.key} className="space-y-2 rounded-xl bg-muted/50 p-3"><div className="flex justify-between text-sm"><span>{labels[item.key]??item.key}</span><b>{item.used} / {item.limit}</b></div><Progress value={item.limit?Math.min(100,item.used/item.limit*100):0}/></div>)}</CardContent></Card>
    <section><h2 className="mb-4 text-xl font-extrabold">الباقات المتاحة</h2><div className="grid gap-5 lg:grid-cols-3">{data.plans.map(plan=><Card key={plan.id} className={plan.recommended?"border-primary shadow-sm":""}><CardHeader><div className="flex justify-between gap-2"><CardTitle>{plan.name}</CardTitle>{plan.recommended&&<Badge>موصى بها</Badge>}</div><CardDescription>{plan.description}</CardDescription><p className="pt-2 text-3xl font-black">{plan.price} <span className="text-sm">{plan.currency}</span></p><p className="text-xs text-muted-foreground">{plan.duration_days} يومًا</p></CardHeader><CardContent className="space-y-4"><div className="space-y-2 text-sm">{["مزايا الدراسة الأساسية","حدود استخدام عادلة قابلة للإدارة","حفظ كل بياناتك وسجلك"].map(x=><p key={x} className="flex gap-2"><Check className="size-4 text-primary"/>{x}</p>)}</div><PaymentRequestForm planId={plan.id} methods={data.methods}/></CardContent></Card>)}</div></section>
    {data.methods.length>0&&<section><h2 className="mb-3 text-lg font-extrabold">طرق الدفع</h2><div className="grid gap-3 sm:grid-cols-2">{data.methods.map(method=><Card key={method.id}><CardHeader><CardTitle className="text-base">{method.name}</CardTitle><CardDescription>{method.type}</CardDescription></CardHeader><CardContent className="space-y-1 text-sm"><p>{method.account_holder}</p><p dir="ltr" className="text-left">{method.account_number||method.wallet_number||method.iban}</p><p className="text-muted-foreground">{method.instructions}</p></CardContent></Card>)}</div></section>}
    <section><h2 className="mb-3 text-lg font-extrabold">طلبات الدفع</h2><div className="space-y-2">{data.payments.length?data.payments.map(p=><Card key={p.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 py-4"><div><b>{p.plan_name_snapshot}</b><p className="text-xs text-muted-foreground">{p.payment_reference} · {new Date(p.created_at).toLocaleDateString("ar-EG")}</p>{p.rejection_reason&&<p className="text-sm text-destructive">السبب: {p.rejection_reason}</p>}</div><div className="flex items-center gap-2"><a className="text-sm text-primary underline" href={`/api/subscription/receipts/${p.id}`} target="_blank">الإيصال</a><Badge variant={p.status==="approved"?"secondary":p.status==="rejected"?"destructive":"outline"}>{statuses[p.status]??p.status}</Badge></div></CardContent></Card>):<p className="text-sm text-muted-foreground">لا توجد طلبات دفع بعد.</p>}</div></section>
    <section><h2 className="mb-3 text-lg font-extrabold">سجل الاشتراكات</h2><div className="grid gap-2 sm:grid-cols-2">{data.history.map(s=><Card key={s.id}><CardContent className="py-4"><b>{s.plan_name_snapshot}</b><p className="text-sm text-muted-foreground">{new Date(s.starts_at).toLocaleDateString("ar-EG")} — {new Date(s.ends_at).toLocaleDateString("ar-EG")}</p></CardContent></Card>)}</div></section>
  </div>}
