"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdminProfile } from "@/lib/auth";
import { withIdentity } from "@/lib/tutor/db";
import { reviewPayment } from "@/lib/subscriptions/payments";
import { processEmailQueue, requeueEmail, sendSmtpTest, updateSmtpSettings } from "@/lib/email-queue";

const uuid=z.string().uuid();
function refresh(){revalidatePath("/admin/subscriptions");revalidatePath("/dashboard/subscription");}

export async function savePlanAction(form:FormData){const admin=await requireAdminProfile();
  const parsed=z.object({id:z.union([uuid,z.literal("")]),slug:z.string().regex(/^[a-z0-9-]+$/),name:z.string().trim().min(2),price:z.coerce.number().min(0),currency:z.string().trim().toUpperCase().regex(/^[A-Z]{3,8}$/),duration:z.coerce.number().int().positive(),description:z.string().max(1000),sortOrder:z.coerce.number().int(),active:z.boolean(),recommended:z.boolean(),entitlements:z.string()}).safeParse({id:form.get("id")??"",slug:form.get("slug"),name:form.get("name"),price:form.get("price"),currency:form.get("currency"),duration:form.get("duration"),description:form.get("description")??"",sortOrder:form.get("sortOrder")??0,active:form.get("active")==="on",recommended:form.get("recommended")==="on",entitlements:form.get("entitlements")});
  if(!parsed.success)throw new Error(parsed.error.issues[0]?.message??"بيانات الباقة غير صالحة");
  let entitlements:Record<string,boolean|number|string>;try{entitlements=JSON.parse(parsed.data.entitlements);if(!entitlements||Array.isArray(entitlements)||Object.values(entitlements).some(v=>!["boolean","number","string"].includes(typeof v)))throw new Error();}catch{throw new Error("Entitlements يجب أن تكون JSON object بقيم بسيطة");}
  await withIdentity(admin.user_id,async db=>{let planId=parsed.data.id;if(planId){await db.query(`update subscription_plans set slug=$2,name=$3,price=$4,currency=$5,duration_days=$6,description=$7,sort_order=$8,active=$9,recommended=$10 where id=$1`,[planId,parsed.data.slug,parsed.data.name,parsed.data.price,parsed.data.currency,parsed.data.duration,parsed.data.description,parsed.data.sortOrder,parsed.data.active,parsed.data.recommended]);}
    else{planId=(await db.query<{id:string}>(`insert into subscription_plans(slug,name,price,currency,duration_days,description,sort_order,active,recommended) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning id`,[parsed.data.slug,parsed.data.name,parsed.data.price,parsed.data.currency,parsed.data.duration,parsed.data.description,parsed.data.sortOrder,parsed.data.active,parsed.data.recommended])).rows[0].id;}
    for(const [key,value] of Object.entries(entitlements)){if(!/^[a-z][a-z0-9_]{1,80}$/.test(key))throw new Error(`Entitlement key غير صالح: ${key}`);await db.query(`insert into plan_entitlements(plan_id,feature_key,value) values($1,$2,$3) on conflict(plan_id,feature_key) do update set value=excluded.value,updated_at=now()`,[planId,key,JSON.stringify(value)]);}
    await db.query("insert into admin_audit_logs(event_type,admin_id,metadata) values($1,$2,$3)",[parsed.data.id?"PLAN_UPDATED":"PLAN_CREATED",admin.user_id,JSON.stringify({planId,keys:Object.keys(entitlements)})]);});refresh();}

export async function savePaymentMethodAction(form:FormData){const admin=await requireAdminProfile();const parsed=z.object({id:z.union([uuid,z.literal("")]),name:z.string().trim().min(2),type:z.string().trim().min(2),accountHolder:z.string(),accountNumber:z.string(),iban:z.string(),walletNumber:z.string(),instructions:z.string(),sortOrder:z.coerce.number().int(),active:z.boolean()}).safeParse({id:form.get("id")??"",name:form.get("name"),type:form.get("type"),accountHolder:form.get("accountHolder")??"",accountNumber:form.get("accountNumber")??"",iban:form.get("iban")??"",walletNumber:form.get("walletNumber")??"",instructions:form.get("instructions")??"",sortOrder:form.get("sortOrder")??0,active:form.get("active")==="on"});if(!parsed.success)throw new Error("بيانات وسيلة الدفع غير صالحة");
  await withIdentity(admin.user_id,async db=>{const v=parsed.data;if(v.id)await db.query(`update payment_methods set name=$2,type=$3,account_holder=$4,account_number=$5,iban=$6,wallet_number=$7,instructions=$8,sort_order=$9,active=$10 where id=$1`,[v.id,v.name,v.type,v.accountHolder||null,v.accountNumber||null,v.iban||null,v.walletNumber||null,v.instructions,v.sortOrder,v.active]);else await db.query(`insert into payment_methods(name,type,account_holder,account_number,iban,wallet_number,instructions,sort_order,active) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[v.name,v.type,v.accountHolder||null,v.accountNumber||null,v.iban||null,v.walletNumber||null,v.instructions,v.sortOrder,v.active]);});refresh();}

export async function reviewPaymentAction(form:FormData){const admin=await requireAdminProfile();const parsed=z.object({id:uuid,decision:z.enum(["approved","rejected"]),reason:z.string().max(500).optional()}).safeParse({id:form.get("id"),decision:form.get("decision"),reason:String(form.get("reason")??"")});if(!parsed.success)throw new Error("قرار المراجعة غير صالح");await reviewPayment(admin.user_id,parsed.data.id,parsed.data.decision,parsed.data.reason);refresh();}

export async function grantSubscriptionAction(form:FormData){const admin=await requireAdminProfile();const parsed=z.object({userId:uuid,planId:uuid,days:z.coerce.number().int().positive().max(3650)}).safeParse({userId:form.get("userId"),planId:form.get("planId"),days:form.get("days")});if(!parsed.success)throw new Error("بيانات المنح غير صالحة");await withIdentity(admin.user_id,async db=>{const plan=(await db.query<{name:string;currency:string}>("select name,currency from subscription_plans where id=$1",[parsed.data.planId])).rows[0];if(!plan)throw new Error("الباقة غير موجودة");const last=(await db.query<{ends_at:string}>("select ends_at from user_subscriptions where user_id=$1 and status not in('cancelled','revoked') and kind<>'trial' and ends_at>now() order by ends_at desc limit 1 for update",[parsed.data.userId])).rows[0];const start=last?new Date(last.ends_at):new Date(),end=new Date(start.getTime()+parsed.data.days*86400000);await db.query(`insert into user_subscriptions(user_id,plan_id,kind,status,starts_at,ends_at,plan_name_snapshot,currency,duration_days_snapshot,created_by,approved_by,notes) values($1,$2,'manual',$3,$4,$5,$6,$7,$8,$9,$9,'منح يدوي من الإدارة')`,[parsed.data.userId,parsed.data.planId,start.getTime()>Date.now()?"scheduled":"active",start.toISOString(),end.toISOString(),plan.name,plan.currency,parsed.data.days,admin.user_id]);await db.query("insert into admin_audit_logs(event_type,admin_id,target_user_id,metadata) values('SUBSCRIPTION_GRANTED',$1,$2,$3)",[admin.user_id,parsed.data.userId,JSON.stringify({planId:parsed.data.planId,days:parsed.data.days})]);});refresh();}

export async function resetTrialAction(form:FormData){const admin=await requireAdminProfile(),userId=uuid.parse(form.get("userId"));await withIdentity(admin.user_id,async db=>{const days=Number((await db.query<{value:number}>("select value from settings where key='trial_duration_days'")).rows[0]?.value??3);await db.query("update user_trials set starts_at=now(),ends_at=now()+($2*interval '1 day'),reset_count=reset_count+1 where user_id=$1",[userId,days]);await db.query("delete from subscription_usage where user_id=$1 and scope_type='trial'",[userId]);await db.query("insert into admin_audit_logs(event_type,admin_id,target_user_id) values('TRIAL_RESET',$1,$2)",[admin.user_id,userId]);});refresh();}
export async function cancelSubscriptionAction(form:FormData){const admin=await requireAdminProfile();const parsed=z.object({userId:uuid,mode:z.enum(["cancelled","revoked"])}).parse({userId:form.get("userId"),mode:form.get("mode")});await withIdentity(admin.user_id,async db=>{const rows=await db.query<{id:string}>(`update user_subscriptions set status=$2,cancelled_at=now(),updated_at=now() where user_id=$1 and kind<>'trial' and status in('active','scheduled') returning id`,[parsed.userId,parsed.mode]);await db.query("insert into admin_audit_logs(event_type,admin_id,target_user_id,metadata) values($1,$2,$3,$4)",[parsed.mode==="revoked"?"SUBSCRIPTION_REVOKED":"SUBSCRIPTION_CANCELLED",admin.user_id,parsed.userId,JSON.stringify({subscriptionIds:rows.rows.map(r=>r.id)})]);});refresh();}

export async function updateSmtpAction(form:FormData){const admin=await requireAdminProfile();const parsed=z.object({host:z.string().trim().min(1),port:z.coerce.number().int().min(1).max(65535),username:z.string(),password:z.string(),encryption:z.enum(["none","starttls","tls"]),fromName:z.string().trim().min(1),fromEmail:z.string().email()}).parse({host:form.get("host"),port:form.get("port"),username:form.get("username")??"",password:form.get("password")??"",encryption:form.get("encryption"),fromName:form.get("fromName"),fromEmail:form.get("fromEmail")});await updateSmtpSettings(admin.user_id,parsed);revalidatePath("/admin/subscriptions/email");}
export async function testSmtpAction(form:FormData){await requireAdminProfile();const email=z.string().email().parse(form.get("email"));await sendSmtpTest(email);}
export async function retryEmailAction(form:FormData){const admin=await requireAdminProfile(),id=uuid.parse(form.get("id"));await requeueEmail(admin.user_id,id);await processEmailQueue(5);revalidatePath("/admin/subscriptions/email");}
export async function saveTemplateAction(form:FormData){const admin=await requireAdminProfile();const parsed=z.object({key:z.string().regex(/^[a-z0-9_]+$/),subject:z.string().min(1),html:z.string().min(1),text:z.string().min(1),active:z.boolean()}).parse({key:form.get("key"),subject:form.get("subject"),html:form.get("html"),text:form.get("text"),active:form.get("active")==="on"});await withIdentity(admin.user_id,db=>db.query("update email_templates set subject=$2,html_body=$3,text_body=$4,active=$5,updated_at=now() where template_key=$1",[parsed.key,parsed.subject,parsed.html,parsed.text,parsed.active]));revalidatePath("/admin/subscriptions/email");}

export async function updateSubscriptionSettingsAction(form:FormData){const admin=await requireAdminProfile();const parsed=z.object({trialDays:z.coerce.number().int().min(1).max(30),trialAi:z.coerce.number().int().min(1).max(1000),trialImages:z.coerce.number().int().min(0).max(1000),trialFiles:z.coerce.number().int().min(0).max(1000),trialStudyPacks:z.coerce.number().int().min(0).max(1000),trialQuizzes:z.coerce.number().int().min(0).max(1000),graceEnabled:z.boolean(),graceHours:z.coerce.number().int().min(1).max(168)}).parse({trialDays:form.get("trialDays"),trialAi:form.get("trialAi"),trialImages:form.get("trialImages"),trialFiles:form.get("trialFiles"),trialStudyPacks:form.get("trialStudyPacks"),trialQuizzes:form.get("trialQuizzes"),graceEnabled:form.get("graceEnabled")==="on",graceHours:form.get("graceHours")});const values=[['trial_duration_days',parsed.trialDays],['trial_ai_questions_daily',parsed.trialAi],['trial_images_total',parsed.trialImages],['trial_files_total',parsed.trialFiles],['trial_study_pack_total',parsed.trialStudyPacks],['trial_quiz_total',parsed.trialQuizzes],['payment_grace_enabled',parsed.graceEnabled],['payment_grace_hours',parsed.graceHours]] as const;await withIdentity(admin.user_id,async db=>{for(const [key,value] of values)await db.query("insert into settings(key,value) values($1,$2) on conflict(key) do update set value=excluded.value,updated_at=now()",[key,JSON.stringify(value)]);});refresh();}
