import Link from "next/link";
import { requireAdminProfile } from "@/lib/auth";
import { getAdminSubscriptionData } from "@/lib/subscriptions/queries";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { CreditCard,Mail } from "lucide-react";
import { grantSubscriptionAction,reviewPaymentAction,savePaymentMethodAction,savePlanAction,updateSubscriptionSettingsAction } from "./actions";

export default async function AdminSubscriptionsPage({searchParams}:{searchParams:Promise<{status?:string}>}){const admin=await requireAdminProfile();const data=await getAdminSubscriptionData(admin.user_id);const filter=(await searchParams).status??"pending";const payments=filter==="all"?data.payments:data.payments.filter(p=>p.status===filter);const stats=data.stats;
return <div className="page-container mx-auto max-w-7xl space-y-8"><PageHeader icon={CreditCard} eyebrow="الإدارة المالية" title="الاشتراكات والمدفوعات" description="إدارة الباقات والحدود وطلبات الدفع من مصدر مركزي واحد." />
<div className="flex flex-wrap gap-2"><Button nativeButton={false} render={<Link href="/admin/subscriptions/email"><Mail className="size-4"/> البريد وSMTP</Link>}/>{["pending","approved","rejected","all"].map(x=><Button key={x} variant={filter===x?"default":"outline"} nativeButton={false} render={<Link href={`/admin/subscriptions?status=${x}`}>{({pending:"معلقة",approved:"مقبولة",rejected:"مرفوضة",all:"الكل"} as Record<string,string>)[x]}</Link>}/>)}</div>
{stats&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["المشتركون النشطون",stats.active_subscribers],["الفترة التجريبية",stats.trial_users],["تنتهي قريبًا",stats.expiring_soon],["طلبات معلقة",stats.pending_payments],["إيراد الشهر",`${stats.revenue_month} ILS`],["إجمالي الإيراد",`${stats.revenue_total} ILS`],["الأكثر شعبية",stats.popular_plan??"—"],["التحويل لمدفوع",`${stats.conversion_rate}%`]].map(([k,v])=><Card key={String(k)}><CardContent className="py-4"><p className="text-xs text-muted-foreground">{k}</p><p className="text-2xl font-black">{v}</p></CardContent></Card>)}</div>}
<section><Card><CardHeader><CardTitle>إعدادات التجربة ومهلة الدفع</CardTitle></CardHeader><CardContent><form action={updateSubscriptionSettingsAction} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field name="trialDays" label="مدة التجربة بالأيام" type="number" value={Number(data.subscriptionSettings.trial_duration_days??3)}/><Field name="trialAi" label="أسئلة AI يوميًا" type="number" value={Number(data.subscriptionSettings.trial_ai_questions_daily??10)}/><Field name="trialImages" label="الصور خلال التجربة" type="number" value={Number(data.subscriptionSettings.trial_images_total??3)}/><Field name="trialFiles" label="الملفات خلال التجربة" type="number" value={Number(data.subscriptionSettings.trial_files_total??1)}/><Field name="trialStudyPacks" label="حزم الدراسة خلال التجربة" type="number" value={Number(data.subscriptionSettings.trial_study_pack_total??1)}/><Field name="trialQuizzes" label="الاختبارات خلال التجربة" type="number" value={Number(data.subscriptionSettings.trial_quiz_total??3)}/><Field name="graceHours" label="مهلة الدفع بالساعات" type="number" value={Number(data.subscriptionSettings.payment_grace_hours??24)}/><label className="flex items-end gap-2 pb-3"><input name="graceEnabled" type="checkbox" defaultChecked={String(data.subscriptionSettings.payment_grace_enabled)==="true"}/> تفعيل مهلة الطلب المعلق</label><Button type="submit" className="self-end">حفظ الإعدادات</Button></form></CardContent></Card></section>
<section><h2 className="mb-3 text-xl font-extrabold">طلبات الدفع</h2><div className="space-y-3">{payments.map(p=><Card key={p.id}><CardContent className="grid gap-3 py-4 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><b>{p.student_name}</b><Badge variant={p.status==="approved"?"secondary":p.status==="rejected"?"destructive":"outline"}>{p.status}</Badge></div><p className="text-sm">{p.plan_name_snapshot} · {p.amount} {p.currency} · {p.method_name??"وسيلة محذوفة"}</p><p className="text-xs text-muted-foreground">{p.payment_reference} · {new Date(p.created_at).toLocaleString("ar-EG")}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" nativeButton={false} render={<a href={`/api/subscription/receipts/${p.id}`} target="_blank">عرض الإيصال</a>}/>{p.status==="pending"&&<><form action={reviewPaymentAction}><input type="hidden" name="id" value={p.id}/><input type="hidden" name="decision" value="approved"/><Button type="submit" size="sm">قبول وتفعيل</Button></form><form action={reviewPaymentAction} className="flex gap-2"><input type="hidden" name="id" value={p.id}/><input type="hidden" name="decision" value="rejected"/><Input name="reason" placeholder="سبب الرفض" required/><Button type="submit" size="sm" variant="destructive">رفض</Button></form></>}</div></CardContent></Card>)}</div></section>
<section><h2 className="mb-3 text-xl font-extrabold">الباقات</h2><div className="grid gap-4 xl:grid-cols-2">{data.plans.map(plan=><Card key={plan.id}><CardHeader><CardTitle>{plan.name}</CardTitle></CardHeader><CardContent><form action={savePlanAction} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={plan.id}/><Field name="slug" label="Slug" value={plan.slug}/><Field name="name" label="الاسم" value={plan.name}/><Field name="price" label="السعر" value={plan.price} type="number"/><Field name="currency" label="العملة" value={plan.currency}/><Field name="duration" label="المدة بالأيام" value={plan.duration_days} type="number"/><Field name="sortOrder" label="الترتيب" value={plan.sort_order} type="number"/><div className="sm:col-span-2"><Label>الوصف</Label><Textarea name="description" defaultValue={plan.description}/></div><div className="sm:col-span-2"><Label>Entitlements JSON</Label><Textarea className="min-h-48 font-mono text-xs" dir="ltr" name="entitlements" defaultValue={JSON.stringify(plan.entitlements,null,2)}/></div><label><input name="active" type="checkbox" defaultChecked={plan.active}/> مفعلة</label><label><input name="recommended" type="checkbox" defaultChecked={plan.recommended}/> موصى بها</label><Button type="submit" className="sm:col-span-2">حفظ الباقة</Button></form></CardContent></Card>)}<Card><CardHeader><CardTitle>إضافة باقة</CardTitle></CardHeader><CardContent><form action={savePlanAction} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value=""/><Field name="slug" label="Slug"/><Field name="name" label="الاسم"/><Field name="price" label="السعر" type="number"/><Field name="currency" label="العملة" value="ILS"/><Field name="duration" label="المدة بالأيام" type="number"/><Field name="sortOrder" label="الترتيب" value="40" type="number"/><div className="sm:col-span-2"><Label>الوصف</Label><Textarea name="description"/></div><div className="sm:col-span-2"><Label>Entitlements JSON</Label><Textarea dir="ltr" name="entitlements" defaultValue={'{"ai_questions_daily":100,"study_pack_enabled":true}'}/></div><label><input name="active" type="checkbox" defaultChecked/> مفعلة</label><label><input name="recommended" type="checkbox"/> موصى بها</label><Button type="submit" className="sm:col-span-2">إضافة</Button></form></CardContent></Card></div></section>
<section><h2 className="mb-3 text-xl font-extrabold">طرق الدفع</h2><div className="grid gap-4 lg:grid-cols-2">{[...data.methods,{id:"",name:"",type:"",account_holder:null,account_number:null,iban:null,wallet_number:null,instructions:"",active:true,sort_order:99}].map((m)=><Card key={m.id||"new"}><CardHeader><CardTitle>{m.id?m.name:"إضافة وسيلة دفع"}</CardTitle></CardHeader><CardContent><form action={savePaymentMethodAction} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={m.id}/><Field name="name" label="الاسم" value={m.name}/><Field name="type" label="النوع" value={m.type}/><Field name="accountHolder" label="صاحب الحساب" value={m.account_holder??""} required={false}/><Field name="accountNumber" label="رقم الحساب" value={m.account_number??""} required={false}/><Field name="iban" label="IBAN" value={m.iban??""} required={false}/><Field name="walletNumber" label="رقم المحفظة" value={m.wallet_number??""} required={false}/><Field name="sortOrder" label="الترتيب" type="number" value={m.sort_order}/><div className="sm:col-span-2"><Label>التعليمات</Label><Textarea name="instructions" defaultValue={m.instructions}/></div><label><input name="active" type="checkbox" defaultChecked={m.active}/> مفعلة</label><Button type="submit" className="sm:col-span-2">{m.id?"حفظ":"إضافة"}</Button></form></CardContent></Card>)}</div></section>
<section><Card><CardHeader><CardTitle>منح أو تمديد اشتراك يدوي</CardTitle></CardHeader><CardContent><form action={grantSubscriptionAction} className="grid gap-3 md:grid-cols-4"><Field name="userId" label="User UUID"/><div><Label>الباقة</Label><select name="planId" className="h-11 w-full rounded-xl border bg-card px-3">{data.plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><Field name="days" label="عدد الأيام" type="number" value="30"/><Button type="submit" className="self-end">منح / تمديد</Button></form></CardContent></Card></section>
</div>}

function Field({name,label,value="",type="text",required=true}:{name:string;label:string;value?:string|number;type?:string;required?:boolean}){return <div className="space-y-1"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} defaultValue={value} required={required}/></div>}
